using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Captcha_Service.Enums
{
    public enum Error
    {
        ERROR_KEY_DOES_NOT_EXIST,
        ERROR_NO_SLOT_AVAILABLE,
        ERROR_ZERO_CAPTCHA_FILESIZE,
        ERROR_TOO_BIG_CAPTCHA_FILESIZE,
        ERROR_ZERO_BALANCE,
        ERROR_IP_NOT_ALLOWED,
        ERROR_CAPTCHA_UNSOLVABLE,
        ERROR_BAD_DUPLICATES,
        ERROR_NO_SUCH_METHOD,
        ERROR_IMAGE_TYPE_NOT_SUPPORTED,
        ERROR_NO_SUCH_CAPCHA_ID,
        ERROR_EMPTY_COMMENT,
        ERROR_IP_BLOCKED,
        ERROR_TASK_ABSENT,
        ERROR_TASK_NOT_SUPPORTED,
        ERROR_INCORRECT_SESSION_DATA,
        ERROR_PROXY_CONNECT_REFUSED,
        ERROR_PROXY_CONNECT_TIMEOUT,
        ERROR_PROXY_READ_TIMEOUT,
        ERROR_PROXY_BANNED,
        ERROR_PROXY_TRANSPARENT,
        ERROR_RECAPTCHA_TIMEOUT,
        ERROR_RECAPTCHA_INVALID_SITEKEY,
        ERROR_RECAPTCHA_INVALID_DOMAIN,
        ERROR_RECAPTCHA_OLD_BROWSER,
        ERROR_TOKEN_EXPIRED,
        ERROR_PROXY_HAS_NO_IMAGE_SUPPORT,
        ERROR_PROXY_INCOMPATIBLE_HTTP_VERSION,
        ERROR_FACTORY_SERVER_API_CONNECTION_FAILED,
        ERROR_FACTORY_SERVER_BAD_JSON,
        ERROR_FACTORY_SERVER_ERRORID_MISSING,
        ERROR_FACTORY_SERVER_ERRORID_NOT_ZERO,
        ERROR_FACTORY_MISSING_PROPERTY,
        ERROR_FACTORY_PROPERTY_INCORRECT_FORMAT,
        ERROR_FACTORY_ACCESS_DENIED,
        ERROR_FACTORY_SERVER_OPERATION_FAILED,
        ERROR_FACTORY_PLATFORM_OPERATION_FAILED,
        ERROR_FACTORY_PROTOCOL_BROKEN,
        ERROR_FACTORY_TASK_NOT_FOUND,
        ERROR_FACTORY_IS_SANDBOXED,
        ERROR_PROXY_NOT_AUTHORISED,
        ERROR_FUNCAPTCHA_NOT_ALLOWED,
        ERROR_INVISIBLE_RECAPTCHA,
        ERROR_FAILED_LOADING_WIDGET,
    }
}
